export default {
login: "lukassso",
id: 29215167,
node_id: "MDQ6VXNlcjI5MjE1MTY3",
avatar_url: "https://avatars.githubusercontent.com/u/29215167?v=4",
gravatar_id: "",
url: "https://api.github.com/users/lukassso",
html_url: "https://github.com/lukassso",
followers_url: "https://api.github.com/users/lukassso/followers",
following_url: "https://api.github.com/users/lukassso/following{/other_user}",
gists_url: "https://api.github.com/users/lukassso/gists{/gist_id}",
starred_url: "https://api.github.com/users/lukassso/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/lukassso/subscriptions",
organizations_url: "https://api.github.com/users/lukassso/orgs",
repos_url: "https://api.github.com/users/lukassso/repos",
events_url: "https://api.github.com/users/lukassso/events{/privacy}",
received_events_url: "https://api.github.com/users/lukassso/received_events",
type: "User",
site_admin: false,
name: "Zetkolek",
company: null,
blog: "https://www.linkedin.com/in/lukasz-zatyka",
location: "Warsaw, PL",
email: null,
hireable: true,
bio: "Coding is my cardio",
twitter_username: null,
public_repos: 40,
public_gists: 0,
followers: 1,
following: 14,
created_at: "2017-06-05T23:17:33Z",
updated_at: "2021-02-25T17:49:39Z"
}